#JMB 2022 -- Taken from https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes
changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - octocat
  categories:
    - title: Nouvelles User Stories & Features 🎉
      labels:
        - us
        - feature
        - enhancement
    - title: Fix et améliorations 🛠
      labels:
        - bug
        - improve
    - title: Autres changements
      labels:
        - "*"