= SAÉ 3.01 2022-2023
:icons: font
:models: models
:experimental:
:incremental:
:numbered:
:toc: macro
:window: _blank
:correction!:

// Useful definitions
:asciidoc: http://www.methods.co.nz/asciidoc[AsciiDoc]
:icongit: icon:git[]
:git: http://git-scm.com/[{icongit}]
:plantuml: https://plantuml.com/fr/[plantUML]
:vscode: https://code.visualstudio.com/[VS Code]

ifndef::env-github[:icons: font]
// Specific to GitHub
ifdef::env-github[]
:correction:
:!toc-title:
:caution-caption: :fire:
:important-caption: :exclamation:
:note-caption: :paperclip:
:tip-caption: :bulb:
:warning-caption: :warning:
:icongit: Git
endif::[]

// /!\ A MODIFIER !!!
:baseURL: https://github.com/IUT-Blagnac/sae3-01-template

// Tags
image:{baseURL}/actions/workflows/blank.yml/badge.svg[Bidon] 
image:{baseURL}/actions/workflows/build.yml/badge.svg[Build] 
image:{baseURL}/actions/workflows/tests.yml/badge.svg[Tests] 
image:https://img.shields.io/badge/License-MPL%202.0-brightgreen.svg[License: MPL-2.0, link="https://opensource.org/licenses/MPL-2.0"]
//---------------------------------------------------------------

TIP: Pensez à mettre à jour les infos dans ce fichier pour que les badges pointent sur les résultats effectifs de vos intégrations continue ou sur la bonne licence logicielle.

WARNING: Ce dépôt présente le projet à développer dans le cadre de la SAÉ 3.01 du BUT1 Informatique de l'IUT de Blagnac.

Ce fichier `README.adoc` (dont vous lisez sûrement le rendu HTML automatiquement effectué par GitHUb), fait partie du dépôt initial cloné à partir du lien GitHub classroom qui vous a été donné en cours (https://classroom.github.com/a/OUF7gxEa).
Vous trouverez le dépôt "template" qui a servi de base ici : https://github.com/IUT-Blagnac/sae3-01-template. En complément du cours Moodle de la SAE 3.01 (cf. <<liensUtiles>>), ce dépôt template vous permet d'accéder à des exemples d'https://github.com/IUT-Blagnac/sae3-01-template/issues[issues], de https://github.com/IUT-Blagnac/sae3-01-template/releases[releases], ou d'autres artefacts à venir.

toc::[]

== Equipe

Projet est réalisé par::

- https://github.com/Yann-cmd[Yann Guillevic]
- https://github.com/VictorThompsonKeyl[Victor Thompson]
- https://github.com/Anthonycbrl[Anthony Cabrillac]
- https://github.com/leosae06[Léo Douville]
- https://github.com/SylvainHsy[Shiyu Hu]

Tuteur/tutrice enseignant(e) de l'équipe:: mailto:laurent.nonne@univ-tlse2.fr[LN]

== Contexte général

TIP: Cette partie de votre `README.adoc` peut être supprimée ou mise ailleurs.

=== Dépôt initial

Ce dépôt initial a été créé pour que tous les groupes de 2ème année aient les mêmes informations de départ.

Vous y trouverez des fichiers qui peuvent être supprimés s'ils ne vous sont pas utiles :

- `.gitignore` => un fichier minimaliste des éléments à ne pas pousser en général sur vos dépôts (utiliser la commande `git add -f` pour forcer l'ajout d'un fichier Jar qui ne bougera plus, pour archive par exemple).
- `.github` => le répertoire qui contient des éléments de gestion de projet :
** `workflows` => le repertoire qui contient les actions à lancer à chaque push sur votre repo. 
*** `blank.yml` => un exemple bidon mais dont vous pourrez vérifier l’exécution correcte (1er tag)
** `ISSUE_TEMPLATE` => le repertoire qui contient quelques templates pour vos issues.
*** `us.yml` => Exemple de template pour les User Stories
*** `bug.yml` => Exemple de template pour les issues de bug report

TIP: Adaptez ces fichiers à votre projet et à votre organisation. Et inspirez-vous en pour en ajouter.

[[liensUtiles]]
=== Liens utiles

- Le https://webetud.iut-blagnac.fr/course/view.php?id=841[cours Moodle] sur la SAE
- Le dépôt https://github.com/IUT-Blagnac/sae3-01-template[template] qui sert de base à tous les dépôts étudiants.
- Le lien https://classroom.github.com/a/OUF7gxEa[classroom] si besoin.

TIP: Pensez à utiliser les salons Discord dédiés pour poser vos questions.

== Réalisations 

TIP: Mettez ici toutes les informations nécessaire à l'utilisation de votre dépôt (comment on installe votre application, où sont les docs, etc.)

Pour la plupart des documenations ci-dessous, celles-ci ont majoritairement été rangées par sprint. Le sprint 5 est actuellement en cours.

**Partie Base de donnée**

Lien vers les docs BD : https://github.com/IUT-Blagnac/sae3-01-devapp-g1b-5/tree/master/Base%20de%20donn%C3%A9e[ici]

Lien vers les tests BD : https://github.com/IUT-Blagnac/sae3-01-devapp-g1b-5/blob/master/Base%20de%20donn%C3%A9e/Tests/Cahier%20de%20tests%20BD%20V1.adoc[ici]

[cols="1,1"]
|===
|Sprint 3
|https://github.com/IUT-Blagnac/sae3-01-devapp-g1b-5/blob/master/Base%20de%20donn%C3%A9e/Sprint%203/DiagrammeDesClasses%20V3%20G1B%20-%205.pdf[Diagramme des classes V3]

https://github.com/IUT-Blagnac/sae3-01-devapp-g1b-5/blob/master/Base%20de%20donn%C3%A9e/Sprint%203/Sch%C3%A9ma%20relationnel%20V3%20G1B%20-%205.pdf[Schéma relationnel V3]

https://github.com/IUT-Blagnac/sae3-01-devapp-g1b-5/blob/master/Base%20de%20donn%C3%A9e/Sprint%203/dicoDonnee%20V3%20G1B%20-%205.pdf[Dictionnaire des données V3]
|===

[cols="1,1"]
|===
|Sprint 4
|https://github.com/IUT-Blagnac/sae3-01-devapp-g1b-5/blob/master/Base%20de%20donn%C3%A9e/Sprint%204/Avancement%20du%20projet%20Base%20de%20donn%C3%A9e%20Semaine%2050%20G1B%20-5.pdf[Livrable avancement de la BD]

https://github.com/IUT-Blagnac/sae3-01-devapp-g1b-5/blob/master/Base%20de%20donn%C3%A9e/Sprint%204/DiagrammeDesClasses%20V4%20G1B%20-%205.pdf[Diagramme des classes V4]

https://github.com/IUT-Blagnac/sae3-01-devapp-g1b-5/blob/master/Base%20de%20donn%C3%A9e/Sprint%204/Sch%C3%A9ma%20relationnel%20V4%20G1B%20-%205.pdf[Schéma relationnel V4]

https://github.com/IUT-Blagnac/sae3-01-devapp-g1b-5/blob/master/Base%20de%20donn%C3%A9e/Sprint%204/dicoDonnee%20V4%20G1B%20-%205.pdf[Dictionnaire des données V4]

https://github.com/IUT-Blagnac/sae3-01-devapp-g1b-5/tree/master/Base%20de%20donn%C3%A9e/Sprint%204/Scripts[Scripts insertion V4 et création des données V4]
|===

[cols="1,1"]
|===
|Sprint 5
|https://github.com/IUT-Blagnac/sae3-01-devapp-g1b-5/blob/master/Base%20de%20donn%C3%A9e/Sprint%205/Avancement%20du%20projet%20Base%20de%20donn%C3%A9e%20Semaine%2001.pdf[Livrable avancement de la BD]

https://github.com/IUT-Blagnac/sae3-01-devapp-g1b-5/blob/master/Base%20de%20donn%C3%A9e/Sprint%205/Cahier%20de%20tests%20BD%20V5.adoc[cahier de test V5]

https://github.com/IUT-Blagnac/sae3-01-devapp-g1b-5/blob/master/Base%20de%20donn%C3%A9e/Sprint%205/D%C3%A9clencheurs.txt[Nos déclencheurs]

https://github.com/IUT-Blagnac/sae3-01-devapp-g1b-5/blob/master/Base%20de%20donn%C3%A9e/Sprint%205/Package%20et%20fonction.txt[Nos packages et fonctions]

https://github.com/IUT-Blagnac/sae3-01-devapp-g1b-5/blob/master/Base%20de%20donn%C3%A9e/Sprint%205/Proc%C3%A9dures.txt[Nos procédures]
|===

**Partie Développement web**

[cols="1,1"]
|===
|Sprint 3
|https://github.com/IUT-Blagnac/sae3-01-devapp-g1b-5/blob/master/Site%20e-commerce%20Cheribou/assets/docs/Sprint%203/Charte_Graphique_PHP_G1B%20-%205.pdf[Charte graphique V1]

https://github.com/IUT-Blagnac/sae3-01-devapp-g1b-5/blob/master/Site%20e-commerce%20Cheribou/assets/docs/Sprint%203/SEP%20G1B%20-%205.pdf[SEP]

Header, footer, menus(avec css)

Charte graphique index.php(avec css)

Charte graphique panier.php(avec css)

|===

[cols="1,1"]
|===
|Sprint 4
|https://github.com/IUT-Blagnac/sae3-01-devapp-g1b-5/blob/master/Site%20e-commerce%20Cheribou/assets/docs/Sprint%204/Avancement%20du%20projet%20Dev%20Web%20semaine%2050%20G1B%20-%205.pdf[Livrable avancement du site web]

Charte graphique Bonbon.php (avec css)

Finalisation Header et footer

Charte graphique Contact.php (avec css)

Charte graphique Compte.php (avec css)
|===

[cols="1,1"]
|===
|Sprint 5
|https://github.com/IUT-Blagnac/sae3-01-devapp-g1b-5/blob/master/Site%20e-commerce%20Cheribou/assets/docs/Sprint%205/Avancement_du_projet_Dev_Web_semaine_01_G1B_-_5.pdf[Livrable avancement du site web]

Finalisation menus (PHP)

Finalisation Contact.php (PHP)

Finalisation index.php (PHP)

Finalisation Compte.php (PHP)

Finalisation Bonbon.php (PHP)

Finalisation InfosCompte.php (PHP)

Finalisation de modification des données client + sessions et cookies

Charte graphique detailProduit.php (avec css)
|===

Lien vers les fichiers Dev Web : https://github.com/IUT-Blagnac/sae3-01-devapp-g1b-5/tree/master/Site%20e-commerce%20Cheribou[ici]

Lien vers les docs Dev Web : https://github.com/IUT-Blagnac/sae3-01-devapp-g1b-5/tree/master/Site%20e-commerce%20Cheribou/assets/docs[ici]

**Partie JAVA**

pas encore disponible


**Partie Python**

Lien vers les programmes Python : https://github.com/IUT-Blagnac/sae3-01-devapp-g1b-5/tree/master/Programmes%20python[ici]

Lien vers les docs Python : https://github.com/IUT-Blagnac/sae3-01-devapp-g1b-5/tree/master/Programmes%20python/Docs%20Python[ici]

Quelques tests Python ont été codé pour vous permettre de tester le programmes principal. Vous pourrez les retrouver : 
https://github.com/IUT-Blagnac/sae3-01-devapp-g1b-5/tree/master/Programmes%20python/Tests[ici]

Notre programme Python utilise la librairie paho-mqtt. Si vous n'avez pas installé celle-ci sur Ubuntu, vous pouvez l'installer avec cette commande :
  `sudo pip3 install paho-mqtt`
  
[cols="1,1"]
|===
|Sprint 3
|Connexion aux services mqtt et extraction des données des capteurs

Réalisation d'un fichier de configuration

Ecriture des données dans un fichier texte

Gestion des seuils maximaux des données
|===

[cols="1,1"]
|===
|Sprint 4
|Gestion de la fréquence d'émission des données

Réalisation des premiers tests
|===

[cols="1,1"]
|===
|Sprint 5
|https://github.com/IUT-Blagnac/sae3-01-devapp-g1b-5/blob/master/Programmes%20python/Tests/Cahier%20de%20tests%20Python%20V1.adoc[Cahier de test Python V1]
|===


**Partie Gestion de projet**

[cols="1,1"]
|===
|Sprint 1
|https://github.com/IUT-Blagnac/sae3-01-devapp-g1b-5/blob/master/GPO/Sprint%201/CDCF.pdf[CDCF]

https://github.com/IUT-Blagnac/sae3-01-devapp-g1b-5/blob/master/GPO/Sprint%201/CDCT.pdf[CDCT]

https://github.com/IUT-Blagnac/sae3-01-devapp-g1b-5/blob/master/GPO/Sprint%201/DCE%20SAE.pdf[DCE]
|===

[cols="1,1"]
|===
|Sprint 2
|https://github.com/IUT-Blagnac/sae3-01-devapp-g1b-5/blob/master/GPO/Sprint%202/Speed%20Dating%20G1B%20-%205.pdf[Compte rendue du speed dating]
|===

[cols="1,1"]
|===
|Sprint 3
|https://github.com/IUT-Blagnac/sae3-01-devapp-g1b-5/blob/master/GPO/Sprint%203/Backlog%20de%20sprint%20(sprint%203).pdf[Backlog de sprint 3]

https://github.com/IUT-Blagnac/sae3-01-devapp-g1b-5/blob/master/GPO/Sprint%203/Compte%20rendu%20de%20r%C3%A9union%20G1B%20-%205.pdf[Compte rendue de réunion semaine 49]

https://github.com/IUT-Blagnac/sae3-01-devapp-g1b-5/blob/master/GPO/Sprint%203/Ordre%20Du%20Jour%20semaine%2049%20G1B%20-5.pdf[Ordre du jour semaine 49]
|===

[cols="1,1"]
|===
|Sprint 4
|https://github.com/IUT-Blagnac/sae3-01-devapp-g1b-5/blob/master/GPO/Sprint%204/Backlog%20de%20sprint%20(sprint%204).pdf[Backlog de sprint 4]

https://github.com/IUT-Blagnac/sae3-01-devapp-g1b-5/blob/master/GPO/Sprint%204/Compte%20rendu%20de%20r%C3%A9union%20semaine%2050%20G1B%20-5.pdf[Compte rendue de réunion semaine 50]

https://github.com/IUT-Blagnac/sae3-01-devapp-g1b-5/blob/master/GPO/Sprint%204/Ordre%20du%20Jour%20semaine%2050%20G1B%20-%205.pdf[Ordre du jour semaine 50]

https://github.com/IUT-Blagnac/sae3-01-devapp-g1b-5/blob/master/GPO/Sprint%204/Analyse%20semaine%2050%20G1B%20-5.pdf[Analyse semaine 50]
|===

[cols="1,1"]
|===
|Sprint 5
|https://github.com/IUT-Blagnac/sae3-01-devapp-g1b-5/blob/master/GPO/Sprint%205/Backlog%20de%20sprint%20(sprint%205).pdf[Backlog de sprint 5]

https://github.com/IUT-Blagnac/sae3-01-devapp-g1b-5/blob/master/GPO/Sprint%205/Compte%20rendu%20de%20r%C3%A9union%20semaine%2001%20G1B%20-5.pdf[Compte rendue de réunion semaine 01]

https://github.com/IUT-Blagnac/sae3-01-devapp-g1b-5/blob/master/GPO/Sprint%205/Ordre%20du%20Jour%20semaine%2001%20G1B%20-%205.pdf[Ordre du jour semaine 01]

https://github.com/IUT-Blagnac/sae3-01-devapp-g1b-5/blob/master/GPO/Sprint%205/Analyse%20semaine%2001%20G1B%20-5.pdf[Analyse semaine 01]
|===

== Gestion de projet & Qualité

Chaque sprint (semaine) vous devrez livrer une nouvelle version de votre application (release).
Utilisez pour cela les fonctionnalités de GitHub pour les https://docs.github.com/en/repositories/releasing-projects-on-github[Releases].

De plus ce fichier `README.adoc` devra être à jour des informations suivantes :

- Version courante : https://github.com/IUT-Blagnac/sae3-01-devapp-g1b-5/releases/tag/V3[V3]
- Lien vers la doc technique : https://github.com/IUT-Blagnac/sae3-01-devapp-g1b-5/blob/master/Site%20e-commerce%20Cheribou/assets/docs/Documentation_technique.adoc[ici]
- Lien vers la doc utilisateur : https://github.com/IUT-Blagnac/sae3-01-devapp-g1b-5/blob/master/Site%20e-commerce%20Cheribou/assets/docs/Documentation_utilisateur.adoc[ici]
- Liste des (ou lien vers les) User Stories (ToDo/Ongoing/Done) et % restant : 

Pour la partie python https://github.com/orgs/IUT-Blagnac/projects/43[ici]

Pour la partie site d'E-commerce https://github.com/orgs/IUT-Blagnac/projects/6/views/1[ici]
  
- Tests unitaires et plans de test

Pour la partie base de donnée : https://github.com/IUT-Blagnac/sae3-01-devapp-g1b-5/blob/master/Base%20de%20donn%C3%A9e/Tests/Cahier%20de%20tests%20BD%20V1.adoc[ici]

Pour la partie python : https://github.com/IUT-Blagnac/sae3-01-devapp-g1b-5/blob/master/Programmes%20python/Tests/Cahier%20de%20tests%20Python%20V1.adoc[ici]

- Indicateurs de qualité du code (dette technique)
- ... tout autre élément que vous jugerez utiles pour démontrer la qualité de votre application


=== Évaluations hebdomadaires



NOTE: Les notes ci-dessous sont mises à jour directement par les enseignants responsables de la compétence 5.



ifdef::env-github[]

image:https://docs.google.com/spreadsheets/d/e/2PACX-1vTc3HJJ9iSI4aa2I9a567wX1AUEmgGrQsPl7tHGSAJ_Z-lzWXwYhlhcVIhh5vCJxoxHXYKjSLetP6NS/pubchart?oid=1826607166&amp;format=image[link=https://docs.google.com/spreadsheets/d/e/2PACX-1vTc3HJJ9iSI4aa2I9a567wX1AUEmgGrQsPl7tHGSAJ_Z-lzWXwYhlhcVIhh5vCJxoxHXYKjSLetP6NS/pubchart?oid=1826607166&amp;format=image]

endif::[]



ifndef::env-github[]

++++

<iframe width="786" height="430" seamless frameborder="0" scrolling="no" src="[https://docs.google.com/spreadsheets/d/e/2PACX-1vTc3HJJ9iSI4aa2I9a567wX1AUEmgGrQsPl7tHGSAJ_Z-lzWXwYhlhcVIhh5vCJxoxHXYKjSLetP6NS/pubchart?oid=1826607166&amp;format=image](https://docs.google.com/spreadsheets/d/e/2PACX-1vTc3HJJ9iSI4aa2I9a567wX1AUEmgGrQsPl7tHGSAJ_Z-lzWXwYhlhcVIhh5vCJxoxHXYKjSLetP6NS/pubchart?oid=1826607166&amp%3Bformat=image&authuser=0)"></iframe>

++++

endif::[]

•	[ ] Pas beaucoup de progrès dans votre README :-( Il reste. toujours des rubriques que j'aimerai voir se remplir...
•	[ ] Vos numéros de version devraient correspondre au numéro de sprints pour faciliter l'évaluation.
•	[ ] J'ai apprécié la présence des tests, mais pensez à donner les résultats aussi (est-ce qu'ils passent ?)


