= Cahier de test BD 

Réalisé par THOMPSON Victor, GUILLEVIC Yann, CABRILLAC Anthony, DOUVILLE Léo, HU Shiyu (G1B -5)

=== Cadre de tests

L'exécution de ces tests s'est déroulé sur SQLDevelopper via Oracle. Cela permettra de s'assurer que le code répond toujours aux besoins même après d'éventuelles modifications.

== Liste des tests

Une liste de tests, comme son nom l'indique, permet de décrire les différentes actions à conduire afin de réaliser les futurs tests.
Ces listes de tests facilitent ainsi la compréhension et la clarté des actions à mener mais également de faciliter la qualification des problèmes rencontrés au cours de la réalisation d'une action et donc, d'une manière plus générale, de la gestion de celles-ci.


|===
|N° |Nom du Test |Nom de l'élément sur lequel le test est efféctué|Conditions de satisfactions |Validité

|1
|testMaj_Stock_Recip_INSERT_OK
|Déclencheur maj_stock_recipient
|Un client fait une nouvelle commande d'un recipient avec une certaine quantité. Cette quantité est déduite du stock correspondant au recipient choisi.
| ✓

|2
|testMaj_Stock_Recip_UPDATE_OK
|Déclencheur maj_stock_recipient
|Un client modifie la quantité d'un recipient dans sa commande. Cette nouvelle quantité est déduite du stock correspondant au recipient choisi.
| ✓

|3
|testMaj_Stock_Recip_DELETE_OK
|Déclencheur maj_stock_recipient
|Un client abandonne sa commande qui contenait des recipients. La quantité de recipient initialement choisi est ajoutée au stock correspondant au recipient.
| ✓

|4
.6+<.>|Guichetier
|Créditer ou débiter un compte
|Débiter : +
 • Doit pouvoir être affiché dans une liste des opérations effectuées (listview) ; +

 • Ne doit pas pouvoir être crédité d'une somme négative. + 
 → _Message d'erreur : NumberFormatException si somme inférieur à  0, String de la somme en ROUGE et impossibilité de créditer cette somme;_ +

 • Ne doit pas pouvoir être débité d'une somme supérieure à un plafond éventuellement défini. + 
 → _Message d'erreur : "Veuillez renseigner une valeur inférieure au plafond défini." (dans une liste ou sous forme de pop-up)_
 
 Créditer : +
  • Doit pouvoir être affiché dans une liste des opérations effectuées (listview) ; +

 • Ne doit pas pouvoir être crédité d'une somme négative. + 
 → _Message d'erreur : NumberFormatException si somme inférieur à 0, String de la somme en ROUGE et impossibilité de créditer cette somme;_ +

 • Ne doit pas pouvoir être débité d'une somme supérieure à un plafond éventuellement défini. + 
 → _Message d'erreur : "Dépassement du découvert!" (dans une liste ou sous forme de pop-up)_
| ✓

|5
|Créer un compte à partir d'informations complémentaires
|• Doit pouvoir être visible par le créateur du compte ainsi que le chef d'agence (proposée en tant qu'option pour celui-ci) ;

 • Ne doit pas renseigner des informations erronées (message possédant des caractères spéciaux ou ne respectant pas le type attendu). +
 → _Message d'erreur : "Veuillez vérifiez que vos informations renseignées soient valides." (dans une liste ou sous forme de pop-up) ;_ +

 • Ne doit pas pouvoir être crée une seconde fois. +
 → _Message d'erreur : "Le compte que vous avez renseigné existe déjà." (dans une liste ou sous forme de pop-up)_
| ✖

|6
|Effectuer un virement de compte à compte
|• Doit pouvoir être affiché en tant que message complet (virement, montant) dans une listview pour l'émetteur et le bénéficiaire ;
 
 • Ne doit pas pouvoir être crédité ou débité d'une somme négative. + 
 → _Erreur apparaissant sur l'interface du virement : les champs de texte changent de couleur, passant ainsi au rouge;_ +

 • Ne doit pas pouvoir effectuer le virement d'une somme supérieure à un plafond éventuellement défini. + 
 → _Message d'erreur : "Dépassement du découvert !" accompagné des champs de texte également modifiés en rouge;_
 
 • Ne doit pas pouvoir réaliser le virement vers un compte clôturé ou n'existant pas. +
 → _Changement de la requête SQL en ne prenant en considération que les comptes ouverts;_
 
 • Ne doit pas pouvoir réaliser un virement vers lui-même (le même compte) +
 → _Condition vérifiant si le compte dans lequel nous réalisons l'opération figure parmi tous les comptes recherchés. Si c'est le cas, il est retiré pour la procédure du virement, dans le cas échéant, ce ne sera pas le cas._
| ✓

|7
|Clôturer un compte
|• Doit pouvoir être affiché en tant que message dans une liste pour le guichetier et le chef d'agence ;

• Ne doit plus être en interaction par un autre compte afin de réaliser une transaction quelconque, seul la consultation du compte sera possible, aucune autre action sera possible
 
•Peut être réalisé une fois que le solde du compte est null 
 
 
 • Ne doit pas pouvoir clôturer un compte déjà clôturé. +
 → _Le compte est toujours visible par le chef d'agence ainsi que le guichetier mais aucunes actions ne peuvent être faites mise à part consulter le compte
| ✓

|8
|Générer un relevé mensuel d'un compte en PDF
| • Doit pouvoir générer le PDF contenant les opérations d'un compte dans Téléchargements;

• Doit pouvoir ouvrir le PDF une fois le bouton cliqué
| ✖

|9
|Gérer les prélèvements automatiques
|• Doit pouvoir être affiché en tant que message dans une liste pour le guichetier et le chef d'agence ;
 
•Peut être réalisé que si le compte n'est pas clôturé
 
• Ne doit pas renseigner des informations erronées (date non valable). +
→ _Message d'erreur : "Veuillez vérifiez que vos informations renseignées soient valides." (dans une liste ou sous forme de pop-up) ;_ +

• Un prélèvement peut être arrêté, il est toujours consultable mais non modifiable/exécutable

| ✓
|===
