== Documentation installation Python

*Groupe : 1B05*

*GUILLEVIC Yann* +
*THOMPSON Victor* +
*CABRILLAC Anthony* +
*DOUVILLE Léo* +
*HU Shiyu* +

Vous avez récupéré le main.py et le fichier de configuration présent sur ce dépot et vous souhaitez avoir un environnement prêt pour l'utilisation ?
Cette documentation va vous dévoiler toute les étapes nécessaires.

Tous d'abord, vous devez posséder un logiciel capable d'interpréter du code python, comme par exemple pyCharm ou Visual Studio Code.
Lorsque votre logiciel est ouvert, vous pouvez glisser-déposer les fichiers que vous souhaitez exécuter dans votre projet dans le logiciel.

Si vous êtes sur VS Code, vous avez 2 méthodes pour lancer le code : 

- Premièrement, vous pouvez cliquer en haut à gauche sur l'onglet "File" puis "new text file" et choisir le langage python. Vous pourrez ainsi y copier les codes python  que vous aurez récupéré. Pour l'exécuter vous pouvez ouvrir un nouveau terminal et y copier la commande suivante pour exécuter le main.py : `python3 main.py`

N'oubliez pas de d'importer également le fichier de configuration config_yaml.yaml.

- Deuxièmement, vous pouvez installer l'extension python dans le menu des extensions à gauche et lancer directement le code avec l'onglet "exécuter".

Pour ces deux manières, si vous êtes sur Ubuntu par exemple, il vous faudra peut-être installer l'extension paho avec la commande suivante : `sudo pip3 install paho-mqtt`.
